language: generic
dist: xenial
cache: pip

matrix:
  include:
  - os: linux
    env:
    - PYTHON=3.6
  - os: linux
    env:
    - PYTHON=3.7
  - os: osx
    env:
    - PYTHON=3.6
  - os: osx
    env:
    - PYTHON=3.7
  fast_finish: true

notifications:
  email: senwu@cs.stanford.edu

before_install:
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then OS=Linux-x86_64; else OS=MacOSX-x86_64;
  fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update;fi
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libomp; fi
- wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-$OS.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- conda config --set always_yes yes --set changeps1 no
- conda config --add channels conda-forge
- conda update -q conda
- conda install -q conda-build
- if [ -n "$PYTHON" ]; then conda create -q -n test-environment python=${PYTHON};
  fi
- source activate test-environment
- conda install -q pip
- python --version
- pip --version
- |
  if [ "$TRAVIS_OS_NAME" = "linux" ]; then
    if [ "${PYTHON}" = "3.6" ]; then
      pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
    fi
    if [ "${PYTHON}" = "3.7" ]; then
      pip install https://download.pytorch.org/whl/cpu/torch-1.1.0-cp37-cp37m-linux_x86_64.whl
    fi
  fi

install:
- make -s dev
- make check
- make docs
- pip install -q coveralls

script:
- travis_wait 50 coverage run --source=fonduer -m pytest tests

after_success:
- coveralls

deploy:
  provider: pypi
  user: senwu
  password:
    secure: NmMG/E1s2oMS+SlyMzNH5CjLJOfVI5jF8NuvMe2fUvvc7gZ3I5tH2ITmQyqiZ7H01UX8H0hfGu6eJN87JzDE0tptbdhzXZS+SqWC3QwOJCCBvpREXxrV/K5dIvY2m2N1DstIDcqSSp0iM/DT6mN52ketp3bhk/pqML9XqzzYS+T8ulmJJ3ZIV+zOYTkFTo8cHubI/12pk9QLUDnX8S9gvCtneOx6/JU1NrF3H0wtOqfFE52PAFtxnNT/0yv/GA/GgYTlWewHUgKrcJWXCnSAstJ0FT3dcoTcGKEvfUWVE9ez3bII3LO383RCzd17h2Xy49pp6z7lW2V/jdmBs+LpDe5idI2pjkjzaMQDwshn3BD3lKrArr9s7uHWyEDv4oKkGzq98CEiJyKB/qKchGdN1CmZdXB25Qucyo7WezmkCBvHvckSiZTlQh8DHzhiqcyzDhv93+gqqbmOAgwzE3QWGqVgK6VSGpGN9ctHgFnjyhmQCTrJ8loMOwB4vYXUW3UijkCI7pc1AlFYQvj2oMRhzRYqysrNjA6YuYvp8+8b43ejJLG8ArLMf0U0rMb2/oM6/TR94V0Q4R45r+Fhz/9htL77lCrkDeLjfzazJN0fUUZtIu21QY48t9m0kx2h3mqSm+qvqSmtP/NXm1X7YjjkIW8Lb/NTK/5MQJUWC2UE/lw=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    tags: true
    branch: master
    condition: $TRAVIS_OS_NAME = "linux" && $PYTHON = "3.7"
